baseurl: ""

collections:
  notes:
    output: true
    permalink: /notes/:name/
  about_me:
    output: true
    permalink: /about/:name/
  whats_new:
    output: true
    permalink: /whats-new/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "document"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "document"